// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: universe_cs.proto

#ifndef PROTOBUF_universe_5fcs_2eproto__INCLUDED
#define PROTOBUF_universe_5fcs_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
class ActorGetFullDataReq;
class ActorGetFullDataReqDefaultTypeInternal;
extern ActorGetFullDataReqDefaultTypeInternal _ActorGetFullDataReq_default_instance_;
class ActorGetFullDataRsp;
class ActorGetFullDataRspDefaultTypeInternal;
extern ActorGetFullDataRspDefaultTypeInternal _ActorGetFullDataRsp_default_instance_;
class ActorLoginReq;
class ActorLoginReqDefaultTypeInternal;
extern ActorLoginReqDefaultTypeInternal _ActorLoginReq_default_instance_;
class ActorLoginRsp;
class ActorLoginRspDefaultTypeInternal;
extern ActorLoginRspDefaultTypeInternal _ActorLoginRsp_default_instance_;
class ActorLogoutReq;
class ActorLogoutReqDefaultTypeInternal;
extern ActorLogoutReqDefaultTypeInternal _ActorLogoutReq_default_instance_;
class ActorLogoutRsp;
class ActorLogoutRspDefaultTypeInternal;
extern ActorLogoutRspDefaultTypeInternal _ActorLogoutRsp_default_instance_;
class ActorPos;
class ActorPosDefaultTypeInternal;
extern ActorPosDefaultTypeInternal _ActorPos_default_instance_;
class ActorRegisteReq;
class ActorRegisteReqDefaultTypeInternal;
extern ActorRegisteReqDefaultTypeInternal _ActorRegisteReq_default_instance_;
class ActorRegisteRsp;
class ActorRegisteRspDefaultTypeInternal;
extern ActorRegisteRspDefaultTypeInternal _ActorRegisteRsp_default_instance_;
class ActorSetPosReq;
class ActorSetPosReqDefaultTypeInternal;
extern ActorSetPosReqDefaultTypeInternal _ActorSetPosReq_default_instance_;
class ActorSetPosRsp;
class ActorSetPosRspDefaultTypeInternal;
extern ActorSetPosRspDefaultTypeInternal _ActorSetPosRsp_default_instance_;
class UniverseMsg;
class UniverseMsgDefaultTypeInternal;
extern UniverseMsgDefaultTypeInternal _UniverseMsg_default_instance_;
class UniverseMsgBody;
class UniverseMsgBodyDefaultTypeInternal;
extern UniverseMsgBodyDefaultTypeInternal _UniverseMsgBody_default_instance_;
class UniverseMsgHead;
class UniverseMsgHeadDefaultTypeInternal;
extern UniverseMsgHeadDefaultTypeInternal _UniverseMsgHead_default_instance_;

namespace protobuf_universe_5fcs_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_universe_5fcs_2eproto

enum UniverseMsgId {
  UNIVERSE_MSG_ID_ACTOR_REGISTE_REQ = 1,
  UNIVERSE_MSG_ID_ACTOR_REGISTE_RSP = 2,
  UNIVERSE_MSG_ID_ACTOR_LOGIN_REQ = 3,
  UNIVERSE_MSG_ID_ACTOR_LOGIN_RSP = 4,
  UNIVERSE_MSG_ID_ACTOR_LOGOUT_REQ = 5,
  UNIVERSE_MSG_ID_ACTOR_LOGOUT_RSP = 6,
  UNIVERSE_MSG_ID_ACTOR_GET_FULL_DATA_REQ = 7,
  UNIVERSE_MSG_ID_ACTOR_GET_FULL_DATA_RSP = 8,
  UNIVERSE_MSG_ID_ACTOR_SET_POS_REQ = 9,
  UNIVERSE_MSG_ID_ACTOR_SET_POS_RSP = 10
};
bool UniverseMsgId_IsValid(int value);
const UniverseMsgId UniverseMsgId_MIN = UNIVERSE_MSG_ID_ACTOR_REGISTE_REQ;
const UniverseMsgId UniverseMsgId_MAX = UNIVERSE_MSG_ID_ACTOR_SET_POS_RSP;
const int UniverseMsgId_ARRAYSIZE = UniverseMsgId_MAX + 1;

const ::google::protobuf::EnumDescriptor* UniverseMsgId_descriptor();
inline const ::std::string& UniverseMsgId_Name(UniverseMsgId value) {
  return ::google::protobuf::internal::NameOfEnum(
    UniverseMsgId_descriptor(), value);
}
inline bool UniverseMsgId_Parse(
    const ::std::string& name, UniverseMsgId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<UniverseMsgId>(
    UniverseMsgId_descriptor(), name, value);
}
// ===================================================================

class UniverseMsgHead : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UniverseMsgHead) */ {
 public:
  UniverseMsgHead();
  virtual ~UniverseMsgHead();

  UniverseMsgHead(const UniverseMsgHead& from);

  inline UniverseMsgHead& operator=(const UniverseMsgHead& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UniverseMsgHead& default_instance();

  static inline const UniverseMsgHead* internal_default_instance() {
    return reinterpret_cast<const UniverseMsgHead*>(
               &_UniverseMsgHead_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(UniverseMsgHead* other);

  // implements Message ----------------------------------------------

  inline UniverseMsgHead* New() const PROTOBUF_FINAL { return New(NULL); }

  UniverseMsgHead* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UniverseMsgHead& from);
  void MergeFrom(const UniverseMsgHead& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UniverseMsgHead* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 msgId = 1;
  bool has_msgid() const;
  void clear_msgid();
  static const int kMsgIdFieldNumber = 1;
  ::google::protobuf::int32 msgid() const;
  void set_msgid(::google::protobuf::int32 value);

  // required int32 msgLen = 2;
  bool has_msglen() const;
  void clear_msglen();
  static const int kMsgLenFieldNumber = 2;
  ::google::protobuf::int32 msglen() const;
  void set_msglen(::google::protobuf::int32 value);

  // required int32 actorId = 3;
  bool has_actorid() const;
  void clear_actorid();
  static const int kActorIdFieldNumber = 3;
  ::google::protobuf::int32 actorid() const;
  void set_actorid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:UniverseMsgHead)
 private:
  void set_has_msgid();
  void clear_has_msgid();
  void set_has_msglen();
  void clear_has_msglen();
  void set_has_actorid();
  void clear_has_actorid();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 msgid_;
  ::google::protobuf::int32 msglen_;
  ::google::protobuf::int32 actorid_;
  friend struct protobuf_universe_5fcs_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ActorRegisteReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ActorRegisteReq) */ {
 public:
  ActorRegisteReq();
  virtual ~ActorRegisteReq();

  ActorRegisteReq(const ActorRegisteReq& from);

  inline ActorRegisteReq& operator=(const ActorRegisteReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ActorRegisteReq& default_instance();

  static inline const ActorRegisteReq* internal_default_instance() {
    return reinterpret_cast<const ActorRegisteReq*>(
               &_ActorRegisteReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(ActorRegisteReq* other);

  // implements Message ----------------------------------------------

  inline ActorRegisteReq* New() const PROTOBUF_FINAL { return New(NULL); }

  ActorRegisteReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ActorRegisteReq& from);
  void MergeFrom(const ActorRegisteReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ActorRegisteReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 2;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // required int32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ActorRegisteReq)
 private:
  void set_has_id();
  void clear_has_id();
  void set_has_name();
  void clear_has_name();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::int32 id_;
  friend struct protobuf_universe_5fcs_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ActorRegisteRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ActorRegisteRsp) */ {
 public:
  ActorRegisteRsp();
  virtual ~ActorRegisteRsp();

  ActorRegisteRsp(const ActorRegisteRsp& from);

  inline ActorRegisteRsp& operator=(const ActorRegisteRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ActorRegisteRsp& default_instance();

  static inline const ActorRegisteRsp* internal_default_instance() {
    return reinterpret_cast<const ActorRegisteRsp*>(
               &_ActorRegisteRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(ActorRegisteRsp* other);

  // implements Message ----------------------------------------------

  inline ActorRegisteRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  ActorRegisteRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ActorRegisteRsp& from);
  void MergeFrom(const ActorRegisteRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ActorRegisteRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 result = 1;
  bool has_result() const;
  void clear_result();
  static const int kResultFieldNumber = 1;
  ::google::protobuf::int32 result() const;
  void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ActorRegisteRsp)
 private:
  void set_has_result();
  void clear_has_result();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 result_;
  friend struct protobuf_universe_5fcs_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ActorLoginReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ActorLoginReq) */ {
 public:
  ActorLoginReq();
  virtual ~ActorLoginReq();

  ActorLoginReq(const ActorLoginReq& from);

  inline ActorLoginReq& operator=(const ActorLoginReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ActorLoginReq& default_instance();

  static inline const ActorLoginReq* internal_default_instance() {
    return reinterpret_cast<const ActorLoginReq*>(
               &_ActorLoginReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(ActorLoginReq* other);

  // implements Message ----------------------------------------------

  inline ActorLoginReq* New() const PROTOBUF_FINAL { return New(NULL); }

  ActorLoginReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ActorLoginReq& from);
  void MergeFrom(const ActorLoginReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ActorLoginReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ActorLoginReq)
 private:
  void set_has_id();
  void clear_has_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 id_;
  friend struct protobuf_universe_5fcs_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ActorLoginRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ActorLoginRsp) */ {
 public:
  ActorLoginRsp();
  virtual ~ActorLoginRsp();

  ActorLoginRsp(const ActorLoginRsp& from);

  inline ActorLoginRsp& operator=(const ActorLoginRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ActorLoginRsp& default_instance();

  static inline const ActorLoginRsp* internal_default_instance() {
    return reinterpret_cast<const ActorLoginRsp*>(
               &_ActorLoginRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(ActorLoginRsp* other);

  // implements Message ----------------------------------------------

  inline ActorLoginRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  ActorLoginRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ActorLoginRsp& from);
  void MergeFrom(const ActorLoginRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ActorLoginRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 result = 1;
  bool has_result() const;
  void clear_result();
  static const int kResultFieldNumber = 1;
  ::google::protobuf::int32 result() const;
  void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ActorLoginRsp)
 private:
  void set_has_result();
  void clear_has_result();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 result_;
  friend struct protobuf_universe_5fcs_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ActorLogoutReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ActorLogoutReq) */ {
 public:
  ActorLogoutReq();
  virtual ~ActorLogoutReq();

  ActorLogoutReq(const ActorLogoutReq& from);

  inline ActorLogoutReq& operator=(const ActorLogoutReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ActorLogoutReq& default_instance();

  static inline const ActorLogoutReq* internal_default_instance() {
    return reinterpret_cast<const ActorLogoutReq*>(
               &_ActorLogoutReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(ActorLogoutReq* other);

  // implements Message ----------------------------------------------

  inline ActorLogoutReq* New() const PROTOBUF_FINAL { return New(NULL); }

  ActorLogoutReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ActorLogoutReq& from);
  void MergeFrom(const ActorLogoutReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ActorLogoutReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ActorLogoutReq)
 private:
  void set_has_id();
  void clear_has_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 id_;
  friend struct protobuf_universe_5fcs_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ActorLogoutRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ActorLogoutRsp) */ {
 public:
  ActorLogoutRsp();
  virtual ~ActorLogoutRsp();

  ActorLogoutRsp(const ActorLogoutRsp& from);

  inline ActorLogoutRsp& operator=(const ActorLogoutRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ActorLogoutRsp& default_instance();

  static inline const ActorLogoutRsp* internal_default_instance() {
    return reinterpret_cast<const ActorLogoutRsp*>(
               &_ActorLogoutRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(ActorLogoutRsp* other);

  // implements Message ----------------------------------------------

  inline ActorLogoutRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  ActorLogoutRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ActorLogoutRsp& from);
  void MergeFrom(const ActorLogoutRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ActorLogoutRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 reserve = 1;
  bool has_reserve() const;
  void clear_reserve();
  static const int kReserveFieldNumber = 1;
  ::google::protobuf::int32 reserve() const;
  void set_reserve(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ActorLogoutRsp)
 private:
  void set_has_reserve();
  void clear_has_reserve();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 reserve_;
  friend struct protobuf_universe_5fcs_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ActorGetFullDataReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ActorGetFullDataReq) */ {
 public:
  ActorGetFullDataReq();
  virtual ~ActorGetFullDataReq();

  ActorGetFullDataReq(const ActorGetFullDataReq& from);

  inline ActorGetFullDataReq& operator=(const ActorGetFullDataReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ActorGetFullDataReq& default_instance();

  static inline const ActorGetFullDataReq* internal_default_instance() {
    return reinterpret_cast<const ActorGetFullDataReq*>(
               &_ActorGetFullDataReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(ActorGetFullDataReq* other);

  // implements Message ----------------------------------------------

  inline ActorGetFullDataReq* New() const PROTOBUF_FINAL { return New(NULL); }

  ActorGetFullDataReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ActorGetFullDataReq& from);
  void MergeFrom(const ActorGetFullDataReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ActorGetFullDataReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ActorGetFullDataReq)
 private:
  void set_has_id();
  void clear_has_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 id_;
  friend struct protobuf_universe_5fcs_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ActorPos : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ActorPos) */ {
 public:
  ActorPos();
  virtual ~ActorPos();

  ActorPos(const ActorPos& from);

  inline ActorPos& operator=(const ActorPos& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ActorPos& default_instance();

  static inline const ActorPos* internal_default_instance() {
    return reinterpret_cast<const ActorPos*>(
               &_ActorPos_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    8;

  void Swap(ActorPos* other);

  // implements Message ----------------------------------------------

  inline ActorPos* New() const PROTOBUF_FINAL { return New(NULL); }

  ActorPos* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ActorPos& from);
  void MergeFrom(const ActorPos& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ActorPos* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  ::google::protobuf::int32 x() const;
  void set_x(::google::protobuf::int32 value);

  // required int32 y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  ::google::protobuf::int32 y() const;
  void set_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ActorPos)
 private:
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  friend struct protobuf_universe_5fcs_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ActorGetFullDataRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ActorGetFullDataRsp) */ {
 public:
  ActorGetFullDataRsp();
  virtual ~ActorGetFullDataRsp();

  ActorGetFullDataRsp(const ActorGetFullDataRsp& from);

  inline ActorGetFullDataRsp& operator=(const ActorGetFullDataRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ActorGetFullDataRsp& default_instance();

  static inline const ActorGetFullDataRsp* internal_default_instance() {
    return reinterpret_cast<const ActorGetFullDataRsp*>(
               &_ActorGetFullDataRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    9;

  void Swap(ActorGetFullDataRsp* other);

  // implements Message ----------------------------------------------

  inline ActorGetFullDataRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  ActorGetFullDataRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ActorGetFullDataRsp& from);
  void MergeFrom(const ActorGetFullDataRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ActorGetFullDataRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 2;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional .ActorPos pos = 3;
  bool has_pos() const;
  void clear_pos();
  static const int kPosFieldNumber = 3;
  const ::ActorPos& pos() const;
  ::ActorPos* mutable_pos();
  ::ActorPos* release_pos();
  void set_allocated_pos(::ActorPos* pos);

  // optional int32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ActorGetFullDataRsp)
 private:
  void set_has_id();
  void clear_has_id();
  void set_has_name();
  void clear_has_name();
  void set_has_pos();
  void clear_has_pos();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::ActorPos* pos_;
  ::google::protobuf::int32 id_;
  friend struct protobuf_universe_5fcs_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ActorSetPosReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ActorSetPosReq) */ {
 public:
  ActorSetPosReq();
  virtual ~ActorSetPosReq();

  ActorSetPosReq(const ActorSetPosReq& from);

  inline ActorSetPosReq& operator=(const ActorSetPosReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ActorSetPosReq& default_instance();

  static inline const ActorSetPosReq* internal_default_instance() {
    return reinterpret_cast<const ActorSetPosReq*>(
               &_ActorSetPosReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    10;

  void Swap(ActorSetPosReq* other);

  // implements Message ----------------------------------------------

  inline ActorSetPosReq* New() const PROTOBUF_FINAL { return New(NULL); }

  ActorSetPosReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ActorSetPosReq& from);
  void MergeFrom(const ActorSetPosReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ActorSetPosReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .ActorPos pos = 3;
  bool has_pos() const;
  void clear_pos();
  static const int kPosFieldNumber = 3;
  const ::ActorPos& pos() const;
  ::ActorPos* mutable_pos();
  ::ActorPos* release_pos();
  void set_allocated_pos(::ActorPos* pos);

  // @@protoc_insertion_point(class_scope:ActorSetPosReq)
 private:
  void set_has_pos();
  void clear_has_pos();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::ActorPos* pos_;
  friend struct protobuf_universe_5fcs_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ActorSetPosRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ActorSetPosRsp) */ {
 public:
  ActorSetPosRsp();
  virtual ~ActorSetPosRsp();

  ActorSetPosRsp(const ActorSetPosRsp& from);

  inline ActorSetPosRsp& operator=(const ActorSetPosRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ActorSetPosRsp& default_instance();

  static inline const ActorSetPosRsp* internal_default_instance() {
    return reinterpret_cast<const ActorSetPosRsp*>(
               &_ActorSetPosRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    11;

  void Swap(ActorSetPosRsp* other);

  // implements Message ----------------------------------------------

  inline ActorSetPosRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  ActorSetPosRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ActorSetPosRsp& from);
  void MergeFrom(const ActorSetPosRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ActorSetPosRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 result = 1;
  bool has_result() const;
  void clear_result();
  static const int kResultFieldNumber = 1;
  ::google::protobuf::int32 result() const;
  void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ActorSetPosRsp)
 private:
  void set_has_result();
  void clear_has_result();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 result_;
  friend struct protobuf_universe_5fcs_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UniverseMsgBody : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UniverseMsgBody) */ {
 public:
  UniverseMsgBody();
  virtual ~UniverseMsgBody();

  UniverseMsgBody(const UniverseMsgBody& from);

  inline UniverseMsgBody& operator=(const UniverseMsgBody& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UniverseMsgBody& default_instance();

  static inline const UniverseMsgBody* internal_default_instance() {
    return reinterpret_cast<const UniverseMsgBody*>(
               &_UniverseMsgBody_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    12;

  void Swap(UniverseMsgBody* other);

  // implements Message ----------------------------------------------

  inline UniverseMsgBody* New() const PROTOBUF_FINAL { return New(NULL); }

  UniverseMsgBody* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UniverseMsgBody& from);
  void MergeFrom(const UniverseMsgBody& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UniverseMsgBody* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .ActorRegisteReq registeReq = 1;
  bool has_registereq() const;
  void clear_registereq();
  static const int kRegisteReqFieldNumber = 1;
  const ::ActorRegisteReq& registereq() const;
  ::ActorRegisteReq* mutable_registereq();
  ::ActorRegisteReq* release_registereq();
  void set_allocated_registereq(::ActorRegisteReq* registereq);

  // optional .ActorRegisteRsp registeRsp = 2;
  bool has_registersp() const;
  void clear_registersp();
  static const int kRegisteRspFieldNumber = 2;
  const ::ActorRegisteRsp& registersp() const;
  ::ActorRegisteRsp* mutable_registersp();
  ::ActorRegisteRsp* release_registersp();
  void set_allocated_registersp(::ActorRegisteRsp* registersp);

  // optional .ActorLoginReq loginReq = 3;
  bool has_loginreq() const;
  void clear_loginreq();
  static const int kLoginReqFieldNumber = 3;
  const ::ActorLoginReq& loginreq() const;
  ::ActorLoginReq* mutable_loginreq();
  ::ActorLoginReq* release_loginreq();
  void set_allocated_loginreq(::ActorLoginReq* loginreq);

  // optional .ActorLoginRsp loginRsp = 4;
  bool has_loginrsp() const;
  void clear_loginrsp();
  static const int kLoginRspFieldNumber = 4;
  const ::ActorLoginRsp& loginrsp() const;
  ::ActorLoginRsp* mutable_loginrsp();
  ::ActorLoginRsp* release_loginrsp();
  void set_allocated_loginrsp(::ActorLoginRsp* loginrsp);

  // optional .ActorLogoutReq logoutReq = 5;
  bool has_logoutreq() const;
  void clear_logoutreq();
  static const int kLogoutReqFieldNumber = 5;
  const ::ActorLogoutReq& logoutreq() const;
  ::ActorLogoutReq* mutable_logoutreq();
  ::ActorLogoutReq* release_logoutreq();
  void set_allocated_logoutreq(::ActorLogoutReq* logoutreq);

  // optional .ActorLogoutRsp logoutRsp = 6;
  bool has_logoutrsp() const;
  void clear_logoutrsp();
  static const int kLogoutRspFieldNumber = 6;
  const ::ActorLogoutRsp& logoutrsp() const;
  ::ActorLogoutRsp* mutable_logoutrsp();
  ::ActorLogoutRsp* release_logoutrsp();
  void set_allocated_logoutrsp(::ActorLogoutRsp* logoutrsp);

  // optional .ActorGetFullDataReq getFullDataReq = 7;
  bool has_getfulldatareq() const;
  void clear_getfulldatareq();
  static const int kGetFullDataReqFieldNumber = 7;
  const ::ActorGetFullDataReq& getfulldatareq() const;
  ::ActorGetFullDataReq* mutable_getfulldatareq();
  ::ActorGetFullDataReq* release_getfulldatareq();
  void set_allocated_getfulldatareq(::ActorGetFullDataReq* getfulldatareq);

  // optional .ActorGetFullDataRsp getFullDataRsp = 8;
  bool has_getfulldatarsp() const;
  void clear_getfulldatarsp();
  static const int kGetFullDataRspFieldNumber = 8;
  const ::ActorGetFullDataRsp& getfulldatarsp() const;
  ::ActorGetFullDataRsp* mutable_getfulldatarsp();
  ::ActorGetFullDataRsp* release_getfulldatarsp();
  void set_allocated_getfulldatarsp(::ActorGetFullDataRsp* getfulldatarsp);

  // optional .ActorSetPosReq setPosReq = 9;
  bool has_setposreq() const;
  void clear_setposreq();
  static const int kSetPosReqFieldNumber = 9;
  const ::ActorSetPosReq& setposreq() const;
  ::ActorSetPosReq* mutable_setposreq();
  ::ActorSetPosReq* release_setposreq();
  void set_allocated_setposreq(::ActorSetPosReq* setposreq);

  // optional .ActorSetPosRsp setPosRsp = 10;
  bool has_setposrsp() const;
  void clear_setposrsp();
  static const int kSetPosRspFieldNumber = 10;
  const ::ActorSetPosRsp& setposrsp() const;
  ::ActorSetPosRsp* mutable_setposrsp();
  ::ActorSetPosRsp* release_setposrsp();
  void set_allocated_setposrsp(::ActorSetPosRsp* setposrsp);

  // @@protoc_insertion_point(class_scope:UniverseMsgBody)
 private:
  void set_has_registereq();
  void clear_has_registereq();
  void set_has_registersp();
  void clear_has_registersp();
  void set_has_loginreq();
  void clear_has_loginreq();
  void set_has_loginrsp();
  void clear_has_loginrsp();
  void set_has_logoutreq();
  void clear_has_logoutreq();
  void set_has_logoutrsp();
  void clear_has_logoutrsp();
  void set_has_getfulldatareq();
  void clear_has_getfulldatareq();
  void set_has_getfulldatarsp();
  void clear_has_getfulldatarsp();
  void set_has_setposreq();
  void clear_has_setposreq();
  void set_has_setposrsp();
  void clear_has_setposrsp();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::ActorRegisteReq* registereq_;
  ::ActorRegisteRsp* registersp_;
  ::ActorLoginReq* loginreq_;
  ::ActorLoginRsp* loginrsp_;
  ::ActorLogoutReq* logoutreq_;
  ::ActorLogoutRsp* logoutrsp_;
  ::ActorGetFullDataReq* getfulldatareq_;
  ::ActorGetFullDataRsp* getfulldatarsp_;
  ::ActorSetPosReq* setposreq_;
  ::ActorSetPosRsp* setposrsp_;
  friend struct protobuf_universe_5fcs_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UniverseMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UniverseMsg) */ {
 public:
  UniverseMsg();
  virtual ~UniverseMsg();

  UniverseMsg(const UniverseMsg& from);

  inline UniverseMsg& operator=(const UniverseMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UniverseMsg& default_instance();

  static inline const UniverseMsg* internal_default_instance() {
    return reinterpret_cast<const UniverseMsg*>(
               &_UniverseMsg_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    13;

  void Swap(UniverseMsg* other);

  // implements Message ----------------------------------------------

  inline UniverseMsg* New() const PROTOBUF_FINAL { return New(NULL); }

  UniverseMsg* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UniverseMsg& from);
  void MergeFrom(const UniverseMsg& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UniverseMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .UniverseMsgHead msgHead = 1;
  bool has_msghead() const;
  void clear_msghead();
  static const int kMsgHeadFieldNumber = 1;
  const ::UniverseMsgHead& msghead() const;
  ::UniverseMsgHead* mutable_msghead();
  ::UniverseMsgHead* release_msghead();
  void set_allocated_msghead(::UniverseMsgHead* msghead);

  // optional .UniverseMsgBody msgBody = 2;
  bool has_msgbody() const;
  void clear_msgbody();
  static const int kMsgBodyFieldNumber = 2;
  const ::UniverseMsgBody& msgbody() const;
  ::UniverseMsgBody* mutable_msgbody();
  ::UniverseMsgBody* release_msgbody();
  void set_allocated_msgbody(::UniverseMsgBody* msgbody);

  // @@protoc_insertion_point(class_scope:UniverseMsg)
 private:
  void set_has_msghead();
  void clear_has_msghead();
  void set_has_msgbody();
  void clear_has_msgbody();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::UniverseMsgHead* msghead_;
  ::UniverseMsgBody* msgbody_;
  friend struct protobuf_universe_5fcs_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// UniverseMsgHead

// required int32 msgId = 1;
inline bool UniverseMsgHead::has_msgid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UniverseMsgHead::set_has_msgid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UniverseMsgHead::clear_has_msgid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UniverseMsgHead::clear_msgid() {
  msgid_ = 0;
  clear_has_msgid();
}
inline ::google::protobuf::int32 UniverseMsgHead::msgid() const {
  // @@protoc_insertion_point(field_get:UniverseMsgHead.msgId)
  return msgid_;
}
inline void UniverseMsgHead::set_msgid(::google::protobuf::int32 value) {
  set_has_msgid();
  msgid_ = value;
  // @@protoc_insertion_point(field_set:UniverseMsgHead.msgId)
}

// required int32 msgLen = 2;
inline bool UniverseMsgHead::has_msglen() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UniverseMsgHead::set_has_msglen() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UniverseMsgHead::clear_has_msglen() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UniverseMsgHead::clear_msglen() {
  msglen_ = 0;
  clear_has_msglen();
}
inline ::google::protobuf::int32 UniverseMsgHead::msglen() const {
  // @@protoc_insertion_point(field_get:UniverseMsgHead.msgLen)
  return msglen_;
}
inline void UniverseMsgHead::set_msglen(::google::protobuf::int32 value) {
  set_has_msglen();
  msglen_ = value;
  // @@protoc_insertion_point(field_set:UniverseMsgHead.msgLen)
}

// required int32 actorId = 3;
inline bool UniverseMsgHead::has_actorid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UniverseMsgHead::set_has_actorid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UniverseMsgHead::clear_has_actorid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UniverseMsgHead::clear_actorid() {
  actorid_ = 0;
  clear_has_actorid();
}
inline ::google::protobuf::int32 UniverseMsgHead::actorid() const {
  // @@protoc_insertion_point(field_get:UniverseMsgHead.actorId)
  return actorid_;
}
inline void UniverseMsgHead::set_actorid(::google::protobuf::int32 value) {
  set_has_actorid();
  actorid_ = value;
  // @@protoc_insertion_point(field_set:UniverseMsgHead.actorId)
}

// -------------------------------------------------------------------

// ActorRegisteReq

// required int32 id = 1;
inline bool ActorRegisteReq::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ActorRegisteReq::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ActorRegisteReq::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ActorRegisteReq::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 ActorRegisteReq::id() const {
  // @@protoc_insertion_point(field_get:ActorRegisteReq.id)
  return id_;
}
inline void ActorRegisteReq::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:ActorRegisteReq.id)
}

// required string name = 2;
inline bool ActorRegisteReq::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ActorRegisteReq::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ActorRegisteReq::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ActorRegisteReq::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& ActorRegisteReq::name() const {
  // @@protoc_insertion_point(field_get:ActorRegisteReq.name)
  return name_.GetNoArena();
}
inline void ActorRegisteReq::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ActorRegisteReq.name)
}
#if LANG_CXX11
inline void ActorRegisteReq::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ActorRegisteReq.name)
}
#endif
inline void ActorRegisteReq::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ActorRegisteReq.name)
}
inline void ActorRegisteReq::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ActorRegisteReq.name)
}
inline ::std::string* ActorRegisteReq::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:ActorRegisteReq.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ActorRegisteReq::release_name() {
  // @@protoc_insertion_point(field_release:ActorRegisteReq.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ActorRegisteReq::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:ActorRegisteReq.name)
}

// -------------------------------------------------------------------

// ActorRegisteRsp

// required int32 result = 1;
inline bool ActorRegisteRsp::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ActorRegisteRsp::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ActorRegisteRsp::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ActorRegisteRsp::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 ActorRegisteRsp::result() const {
  // @@protoc_insertion_point(field_get:ActorRegisteRsp.result)
  return result_;
}
inline void ActorRegisteRsp::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:ActorRegisteRsp.result)
}

// -------------------------------------------------------------------

// ActorLoginReq

// required int32 id = 1;
inline bool ActorLoginReq::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ActorLoginReq::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ActorLoginReq::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ActorLoginReq::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 ActorLoginReq::id() const {
  // @@protoc_insertion_point(field_get:ActorLoginReq.id)
  return id_;
}
inline void ActorLoginReq::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:ActorLoginReq.id)
}

// -------------------------------------------------------------------

// ActorLoginRsp

// required int32 result = 1;
inline bool ActorLoginRsp::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ActorLoginRsp::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ActorLoginRsp::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ActorLoginRsp::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 ActorLoginRsp::result() const {
  // @@protoc_insertion_point(field_get:ActorLoginRsp.result)
  return result_;
}
inline void ActorLoginRsp::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:ActorLoginRsp.result)
}

// -------------------------------------------------------------------

// ActorLogoutReq

// required int32 id = 1;
inline bool ActorLogoutReq::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ActorLogoutReq::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ActorLogoutReq::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ActorLogoutReq::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 ActorLogoutReq::id() const {
  // @@protoc_insertion_point(field_get:ActorLogoutReq.id)
  return id_;
}
inline void ActorLogoutReq::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:ActorLogoutReq.id)
}

// -------------------------------------------------------------------

// ActorLogoutRsp

// optional int32 reserve = 1;
inline bool ActorLogoutRsp::has_reserve() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ActorLogoutRsp::set_has_reserve() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ActorLogoutRsp::clear_has_reserve() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ActorLogoutRsp::clear_reserve() {
  reserve_ = 0;
  clear_has_reserve();
}
inline ::google::protobuf::int32 ActorLogoutRsp::reserve() const {
  // @@protoc_insertion_point(field_get:ActorLogoutRsp.reserve)
  return reserve_;
}
inline void ActorLogoutRsp::set_reserve(::google::protobuf::int32 value) {
  set_has_reserve();
  reserve_ = value;
  // @@protoc_insertion_point(field_set:ActorLogoutRsp.reserve)
}

// -------------------------------------------------------------------

// ActorGetFullDataReq

// optional int32 id = 1;
inline bool ActorGetFullDataReq::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ActorGetFullDataReq::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ActorGetFullDataReq::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ActorGetFullDataReq::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 ActorGetFullDataReq::id() const {
  // @@protoc_insertion_point(field_get:ActorGetFullDataReq.id)
  return id_;
}
inline void ActorGetFullDataReq::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:ActorGetFullDataReq.id)
}

// -------------------------------------------------------------------

// ActorPos

// required int32 x = 1;
inline bool ActorPos::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ActorPos::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ActorPos::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ActorPos::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 ActorPos::x() const {
  // @@protoc_insertion_point(field_get:ActorPos.x)
  return x_;
}
inline void ActorPos::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:ActorPos.x)
}

// required int32 y = 2;
inline bool ActorPos::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ActorPos::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ActorPos::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ActorPos::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 ActorPos::y() const {
  // @@protoc_insertion_point(field_get:ActorPos.y)
  return y_;
}
inline void ActorPos::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:ActorPos.y)
}

// -------------------------------------------------------------------

// ActorGetFullDataRsp

// optional int32 id = 1;
inline bool ActorGetFullDataRsp::has_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ActorGetFullDataRsp::set_has_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ActorGetFullDataRsp::clear_has_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ActorGetFullDataRsp::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 ActorGetFullDataRsp::id() const {
  // @@protoc_insertion_point(field_get:ActorGetFullDataRsp.id)
  return id_;
}
inline void ActorGetFullDataRsp::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:ActorGetFullDataRsp.id)
}

// optional string name = 2;
inline bool ActorGetFullDataRsp::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ActorGetFullDataRsp::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ActorGetFullDataRsp::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ActorGetFullDataRsp::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& ActorGetFullDataRsp::name() const {
  // @@protoc_insertion_point(field_get:ActorGetFullDataRsp.name)
  return name_.GetNoArena();
}
inline void ActorGetFullDataRsp::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ActorGetFullDataRsp.name)
}
#if LANG_CXX11
inline void ActorGetFullDataRsp::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ActorGetFullDataRsp.name)
}
#endif
inline void ActorGetFullDataRsp::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ActorGetFullDataRsp.name)
}
inline void ActorGetFullDataRsp::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ActorGetFullDataRsp.name)
}
inline ::std::string* ActorGetFullDataRsp::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:ActorGetFullDataRsp.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ActorGetFullDataRsp::release_name() {
  // @@protoc_insertion_point(field_release:ActorGetFullDataRsp.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ActorGetFullDataRsp::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:ActorGetFullDataRsp.name)
}

// optional .ActorPos pos = 3;
inline bool ActorGetFullDataRsp::has_pos() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ActorGetFullDataRsp::set_has_pos() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ActorGetFullDataRsp::clear_has_pos() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ActorGetFullDataRsp::clear_pos() {
  if (pos_ != NULL) pos_->::ActorPos::Clear();
  clear_has_pos();
}
inline const ::ActorPos& ActorGetFullDataRsp::pos() const {
  // @@protoc_insertion_point(field_get:ActorGetFullDataRsp.pos)
  return pos_ != NULL ? *pos_
                         : *::ActorPos::internal_default_instance();
}
inline ::ActorPos* ActorGetFullDataRsp::mutable_pos() {
  set_has_pos();
  if (pos_ == NULL) {
    pos_ = new ::ActorPos;
  }
  // @@protoc_insertion_point(field_mutable:ActorGetFullDataRsp.pos)
  return pos_;
}
inline ::ActorPos* ActorGetFullDataRsp::release_pos() {
  // @@protoc_insertion_point(field_release:ActorGetFullDataRsp.pos)
  clear_has_pos();
  ::ActorPos* temp = pos_;
  pos_ = NULL;
  return temp;
}
inline void ActorGetFullDataRsp::set_allocated_pos(::ActorPos* pos) {
  delete pos_;
  pos_ = pos;
  if (pos) {
    set_has_pos();
  } else {
    clear_has_pos();
  }
  // @@protoc_insertion_point(field_set_allocated:ActorGetFullDataRsp.pos)
}

// -------------------------------------------------------------------

// ActorSetPosReq

// optional .ActorPos pos = 3;
inline bool ActorSetPosReq::has_pos() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ActorSetPosReq::set_has_pos() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ActorSetPosReq::clear_has_pos() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ActorSetPosReq::clear_pos() {
  if (pos_ != NULL) pos_->::ActorPos::Clear();
  clear_has_pos();
}
inline const ::ActorPos& ActorSetPosReq::pos() const {
  // @@protoc_insertion_point(field_get:ActorSetPosReq.pos)
  return pos_ != NULL ? *pos_
                         : *::ActorPos::internal_default_instance();
}
inline ::ActorPos* ActorSetPosReq::mutable_pos() {
  set_has_pos();
  if (pos_ == NULL) {
    pos_ = new ::ActorPos;
  }
  // @@protoc_insertion_point(field_mutable:ActorSetPosReq.pos)
  return pos_;
}
inline ::ActorPos* ActorSetPosReq::release_pos() {
  // @@protoc_insertion_point(field_release:ActorSetPosReq.pos)
  clear_has_pos();
  ::ActorPos* temp = pos_;
  pos_ = NULL;
  return temp;
}
inline void ActorSetPosReq::set_allocated_pos(::ActorPos* pos) {
  delete pos_;
  pos_ = pos;
  if (pos) {
    set_has_pos();
  } else {
    clear_has_pos();
  }
  // @@protoc_insertion_point(field_set_allocated:ActorSetPosReq.pos)
}

// -------------------------------------------------------------------

// ActorSetPosRsp

// required int32 result = 1;
inline bool ActorSetPosRsp::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ActorSetPosRsp::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ActorSetPosRsp::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ActorSetPosRsp::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 ActorSetPosRsp::result() const {
  // @@protoc_insertion_point(field_get:ActorSetPosRsp.result)
  return result_;
}
inline void ActorSetPosRsp::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:ActorSetPosRsp.result)
}

// -------------------------------------------------------------------

// UniverseMsgBody

// optional .ActorRegisteReq registeReq = 1;
inline bool UniverseMsgBody::has_registereq() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UniverseMsgBody::set_has_registereq() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UniverseMsgBody::clear_has_registereq() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UniverseMsgBody::clear_registereq() {
  if (registereq_ != NULL) registereq_->::ActorRegisteReq::Clear();
  clear_has_registereq();
}
inline const ::ActorRegisteReq& UniverseMsgBody::registereq() const {
  // @@protoc_insertion_point(field_get:UniverseMsgBody.registeReq)
  return registereq_ != NULL ? *registereq_
                         : *::ActorRegisteReq::internal_default_instance();
}
inline ::ActorRegisteReq* UniverseMsgBody::mutable_registereq() {
  set_has_registereq();
  if (registereq_ == NULL) {
    registereq_ = new ::ActorRegisteReq;
  }
  // @@protoc_insertion_point(field_mutable:UniverseMsgBody.registeReq)
  return registereq_;
}
inline ::ActorRegisteReq* UniverseMsgBody::release_registereq() {
  // @@protoc_insertion_point(field_release:UniverseMsgBody.registeReq)
  clear_has_registereq();
  ::ActorRegisteReq* temp = registereq_;
  registereq_ = NULL;
  return temp;
}
inline void UniverseMsgBody::set_allocated_registereq(::ActorRegisteReq* registereq) {
  delete registereq_;
  registereq_ = registereq;
  if (registereq) {
    set_has_registereq();
  } else {
    clear_has_registereq();
  }
  // @@protoc_insertion_point(field_set_allocated:UniverseMsgBody.registeReq)
}

// optional .ActorRegisteRsp registeRsp = 2;
inline bool UniverseMsgBody::has_registersp() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UniverseMsgBody::set_has_registersp() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UniverseMsgBody::clear_has_registersp() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UniverseMsgBody::clear_registersp() {
  if (registersp_ != NULL) registersp_->::ActorRegisteRsp::Clear();
  clear_has_registersp();
}
inline const ::ActorRegisteRsp& UniverseMsgBody::registersp() const {
  // @@protoc_insertion_point(field_get:UniverseMsgBody.registeRsp)
  return registersp_ != NULL ? *registersp_
                         : *::ActorRegisteRsp::internal_default_instance();
}
inline ::ActorRegisteRsp* UniverseMsgBody::mutable_registersp() {
  set_has_registersp();
  if (registersp_ == NULL) {
    registersp_ = new ::ActorRegisteRsp;
  }
  // @@protoc_insertion_point(field_mutable:UniverseMsgBody.registeRsp)
  return registersp_;
}
inline ::ActorRegisteRsp* UniverseMsgBody::release_registersp() {
  // @@protoc_insertion_point(field_release:UniverseMsgBody.registeRsp)
  clear_has_registersp();
  ::ActorRegisteRsp* temp = registersp_;
  registersp_ = NULL;
  return temp;
}
inline void UniverseMsgBody::set_allocated_registersp(::ActorRegisteRsp* registersp) {
  delete registersp_;
  registersp_ = registersp;
  if (registersp) {
    set_has_registersp();
  } else {
    clear_has_registersp();
  }
  // @@protoc_insertion_point(field_set_allocated:UniverseMsgBody.registeRsp)
}

// optional .ActorLoginReq loginReq = 3;
inline bool UniverseMsgBody::has_loginreq() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UniverseMsgBody::set_has_loginreq() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UniverseMsgBody::clear_has_loginreq() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UniverseMsgBody::clear_loginreq() {
  if (loginreq_ != NULL) loginreq_->::ActorLoginReq::Clear();
  clear_has_loginreq();
}
inline const ::ActorLoginReq& UniverseMsgBody::loginreq() const {
  // @@protoc_insertion_point(field_get:UniverseMsgBody.loginReq)
  return loginreq_ != NULL ? *loginreq_
                         : *::ActorLoginReq::internal_default_instance();
}
inline ::ActorLoginReq* UniverseMsgBody::mutable_loginreq() {
  set_has_loginreq();
  if (loginreq_ == NULL) {
    loginreq_ = new ::ActorLoginReq;
  }
  // @@protoc_insertion_point(field_mutable:UniverseMsgBody.loginReq)
  return loginreq_;
}
inline ::ActorLoginReq* UniverseMsgBody::release_loginreq() {
  // @@protoc_insertion_point(field_release:UniverseMsgBody.loginReq)
  clear_has_loginreq();
  ::ActorLoginReq* temp = loginreq_;
  loginreq_ = NULL;
  return temp;
}
inline void UniverseMsgBody::set_allocated_loginreq(::ActorLoginReq* loginreq) {
  delete loginreq_;
  loginreq_ = loginreq;
  if (loginreq) {
    set_has_loginreq();
  } else {
    clear_has_loginreq();
  }
  // @@protoc_insertion_point(field_set_allocated:UniverseMsgBody.loginReq)
}

// optional .ActorLoginRsp loginRsp = 4;
inline bool UniverseMsgBody::has_loginrsp() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void UniverseMsgBody::set_has_loginrsp() {
  _has_bits_[0] |= 0x00000008u;
}
inline void UniverseMsgBody::clear_has_loginrsp() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void UniverseMsgBody::clear_loginrsp() {
  if (loginrsp_ != NULL) loginrsp_->::ActorLoginRsp::Clear();
  clear_has_loginrsp();
}
inline const ::ActorLoginRsp& UniverseMsgBody::loginrsp() const {
  // @@protoc_insertion_point(field_get:UniverseMsgBody.loginRsp)
  return loginrsp_ != NULL ? *loginrsp_
                         : *::ActorLoginRsp::internal_default_instance();
}
inline ::ActorLoginRsp* UniverseMsgBody::mutable_loginrsp() {
  set_has_loginrsp();
  if (loginrsp_ == NULL) {
    loginrsp_ = new ::ActorLoginRsp;
  }
  // @@protoc_insertion_point(field_mutable:UniverseMsgBody.loginRsp)
  return loginrsp_;
}
inline ::ActorLoginRsp* UniverseMsgBody::release_loginrsp() {
  // @@protoc_insertion_point(field_release:UniverseMsgBody.loginRsp)
  clear_has_loginrsp();
  ::ActorLoginRsp* temp = loginrsp_;
  loginrsp_ = NULL;
  return temp;
}
inline void UniverseMsgBody::set_allocated_loginrsp(::ActorLoginRsp* loginrsp) {
  delete loginrsp_;
  loginrsp_ = loginrsp;
  if (loginrsp) {
    set_has_loginrsp();
  } else {
    clear_has_loginrsp();
  }
  // @@protoc_insertion_point(field_set_allocated:UniverseMsgBody.loginRsp)
}

// optional .ActorLogoutReq logoutReq = 5;
inline bool UniverseMsgBody::has_logoutreq() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void UniverseMsgBody::set_has_logoutreq() {
  _has_bits_[0] |= 0x00000010u;
}
inline void UniverseMsgBody::clear_has_logoutreq() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void UniverseMsgBody::clear_logoutreq() {
  if (logoutreq_ != NULL) logoutreq_->::ActorLogoutReq::Clear();
  clear_has_logoutreq();
}
inline const ::ActorLogoutReq& UniverseMsgBody::logoutreq() const {
  // @@protoc_insertion_point(field_get:UniverseMsgBody.logoutReq)
  return logoutreq_ != NULL ? *logoutreq_
                         : *::ActorLogoutReq::internal_default_instance();
}
inline ::ActorLogoutReq* UniverseMsgBody::mutable_logoutreq() {
  set_has_logoutreq();
  if (logoutreq_ == NULL) {
    logoutreq_ = new ::ActorLogoutReq;
  }
  // @@protoc_insertion_point(field_mutable:UniverseMsgBody.logoutReq)
  return logoutreq_;
}
inline ::ActorLogoutReq* UniverseMsgBody::release_logoutreq() {
  // @@protoc_insertion_point(field_release:UniverseMsgBody.logoutReq)
  clear_has_logoutreq();
  ::ActorLogoutReq* temp = logoutreq_;
  logoutreq_ = NULL;
  return temp;
}
inline void UniverseMsgBody::set_allocated_logoutreq(::ActorLogoutReq* logoutreq) {
  delete logoutreq_;
  logoutreq_ = logoutreq;
  if (logoutreq) {
    set_has_logoutreq();
  } else {
    clear_has_logoutreq();
  }
  // @@protoc_insertion_point(field_set_allocated:UniverseMsgBody.logoutReq)
}

// optional .ActorLogoutRsp logoutRsp = 6;
inline bool UniverseMsgBody::has_logoutrsp() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void UniverseMsgBody::set_has_logoutrsp() {
  _has_bits_[0] |= 0x00000020u;
}
inline void UniverseMsgBody::clear_has_logoutrsp() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void UniverseMsgBody::clear_logoutrsp() {
  if (logoutrsp_ != NULL) logoutrsp_->::ActorLogoutRsp::Clear();
  clear_has_logoutrsp();
}
inline const ::ActorLogoutRsp& UniverseMsgBody::logoutrsp() const {
  // @@protoc_insertion_point(field_get:UniverseMsgBody.logoutRsp)
  return logoutrsp_ != NULL ? *logoutrsp_
                         : *::ActorLogoutRsp::internal_default_instance();
}
inline ::ActorLogoutRsp* UniverseMsgBody::mutable_logoutrsp() {
  set_has_logoutrsp();
  if (logoutrsp_ == NULL) {
    logoutrsp_ = new ::ActorLogoutRsp;
  }
  // @@protoc_insertion_point(field_mutable:UniverseMsgBody.logoutRsp)
  return logoutrsp_;
}
inline ::ActorLogoutRsp* UniverseMsgBody::release_logoutrsp() {
  // @@protoc_insertion_point(field_release:UniverseMsgBody.logoutRsp)
  clear_has_logoutrsp();
  ::ActorLogoutRsp* temp = logoutrsp_;
  logoutrsp_ = NULL;
  return temp;
}
inline void UniverseMsgBody::set_allocated_logoutrsp(::ActorLogoutRsp* logoutrsp) {
  delete logoutrsp_;
  logoutrsp_ = logoutrsp;
  if (logoutrsp) {
    set_has_logoutrsp();
  } else {
    clear_has_logoutrsp();
  }
  // @@protoc_insertion_point(field_set_allocated:UniverseMsgBody.logoutRsp)
}

// optional .ActorGetFullDataReq getFullDataReq = 7;
inline bool UniverseMsgBody::has_getfulldatareq() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void UniverseMsgBody::set_has_getfulldatareq() {
  _has_bits_[0] |= 0x00000040u;
}
inline void UniverseMsgBody::clear_has_getfulldatareq() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void UniverseMsgBody::clear_getfulldatareq() {
  if (getfulldatareq_ != NULL) getfulldatareq_->::ActorGetFullDataReq::Clear();
  clear_has_getfulldatareq();
}
inline const ::ActorGetFullDataReq& UniverseMsgBody::getfulldatareq() const {
  // @@protoc_insertion_point(field_get:UniverseMsgBody.getFullDataReq)
  return getfulldatareq_ != NULL ? *getfulldatareq_
                         : *::ActorGetFullDataReq::internal_default_instance();
}
inline ::ActorGetFullDataReq* UniverseMsgBody::mutable_getfulldatareq() {
  set_has_getfulldatareq();
  if (getfulldatareq_ == NULL) {
    getfulldatareq_ = new ::ActorGetFullDataReq;
  }
  // @@protoc_insertion_point(field_mutable:UniverseMsgBody.getFullDataReq)
  return getfulldatareq_;
}
inline ::ActorGetFullDataReq* UniverseMsgBody::release_getfulldatareq() {
  // @@protoc_insertion_point(field_release:UniverseMsgBody.getFullDataReq)
  clear_has_getfulldatareq();
  ::ActorGetFullDataReq* temp = getfulldatareq_;
  getfulldatareq_ = NULL;
  return temp;
}
inline void UniverseMsgBody::set_allocated_getfulldatareq(::ActorGetFullDataReq* getfulldatareq) {
  delete getfulldatareq_;
  getfulldatareq_ = getfulldatareq;
  if (getfulldatareq) {
    set_has_getfulldatareq();
  } else {
    clear_has_getfulldatareq();
  }
  // @@protoc_insertion_point(field_set_allocated:UniverseMsgBody.getFullDataReq)
}

// optional .ActorGetFullDataRsp getFullDataRsp = 8;
inline bool UniverseMsgBody::has_getfulldatarsp() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void UniverseMsgBody::set_has_getfulldatarsp() {
  _has_bits_[0] |= 0x00000080u;
}
inline void UniverseMsgBody::clear_has_getfulldatarsp() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void UniverseMsgBody::clear_getfulldatarsp() {
  if (getfulldatarsp_ != NULL) getfulldatarsp_->::ActorGetFullDataRsp::Clear();
  clear_has_getfulldatarsp();
}
inline const ::ActorGetFullDataRsp& UniverseMsgBody::getfulldatarsp() const {
  // @@protoc_insertion_point(field_get:UniverseMsgBody.getFullDataRsp)
  return getfulldatarsp_ != NULL ? *getfulldatarsp_
                         : *::ActorGetFullDataRsp::internal_default_instance();
}
inline ::ActorGetFullDataRsp* UniverseMsgBody::mutable_getfulldatarsp() {
  set_has_getfulldatarsp();
  if (getfulldatarsp_ == NULL) {
    getfulldatarsp_ = new ::ActorGetFullDataRsp;
  }
  // @@protoc_insertion_point(field_mutable:UniverseMsgBody.getFullDataRsp)
  return getfulldatarsp_;
}
inline ::ActorGetFullDataRsp* UniverseMsgBody::release_getfulldatarsp() {
  // @@protoc_insertion_point(field_release:UniverseMsgBody.getFullDataRsp)
  clear_has_getfulldatarsp();
  ::ActorGetFullDataRsp* temp = getfulldatarsp_;
  getfulldatarsp_ = NULL;
  return temp;
}
inline void UniverseMsgBody::set_allocated_getfulldatarsp(::ActorGetFullDataRsp* getfulldatarsp) {
  delete getfulldatarsp_;
  getfulldatarsp_ = getfulldatarsp;
  if (getfulldatarsp) {
    set_has_getfulldatarsp();
  } else {
    clear_has_getfulldatarsp();
  }
  // @@protoc_insertion_point(field_set_allocated:UniverseMsgBody.getFullDataRsp)
}

// optional .ActorSetPosReq setPosReq = 9;
inline bool UniverseMsgBody::has_setposreq() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void UniverseMsgBody::set_has_setposreq() {
  _has_bits_[0] |= 0x00000100u;
}
inline void UniverseMsgBody::clear_has_setposreq() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void UniverseMsgBody::clear_setposreq() {
  if (setposreq_ != NULL) setposreq_->::ActorSetPosReq::Clear();
  clear_has_setposreq();
}
inline const ::ActorSetPosReq& UniverseMsgBody::setposreq() const {
  // @@protoc_insertion_point(field_get:UniverseMsgBody.setPosReq)
  return setposreq_ != NULL ? *setposreq_
                         : *::ActorSetPosReq::internal_default_instance();
}
inline ::ActorSetPosReq* UniverseMsgBody::mutable_setposreq() {
  set_has_setposreq();
  if (setposreq_ == NULL) {
    setposreq_ = new ::ActorSetPosReq;
  }
  // @@protoc_insertion_point(field_mutable:UniverseMsgBody.setPosReq)
  return setposreq_;
}
inline ::ActorSetPosReq* UniverseMsgBody::release_setposreq() {
  // @@protoc_insertion_point(field_release:UniverseMsgBody.setPosReq)
  clear_has_setposreq();
  ::ActorSetPosReq* temp = setposreq_;
  setposreq_ = NULL;
  return temp;
}
inline void UniverseMsgBody::set_allocated_setposreq(::ActorSetPosReq* setposreq) {
  delete setposreq_;
  setposreq_ = setposreq;
  if (setposreq) {
    set_has_setposreq();
  } else {
    clear_has_setposreq();
  }
  // @@protoc_insertion_point(field_set_allocated:UniverseMsgBody.setPosReq)
}

// optional .ActorSetPosRsp setPosRsp = 10;
inline bool UniverseMsgBody::has_setposrsp() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void UniverseMsgBody::set_has_setposrsp() {
  _has_bits_[0] |= 0x00000200u;
}
inline void UniverseMsgBody::clear_has_setposrsp() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void UniverseMsgBody::clear_setposrsp() {
  if (setposrsp_ != NULL) setposrsp_->::ActorSetPosRsp::Clear();
  clear_has_setposrsp();
}
inline const ::ActorSetPosRsp& UniverseMsgBody::setposrsp() const {
  // @@protoc_insertion_point(field_get:UniverseMsgBody.setPosRsp)
  return setposrsp_ != NULL ? *setposrsp_
                         : *::ActorSetPosRsp::internal_default_instance();
}
inline ::ActorSetPosRsp* UniverseMsgBody::mutable_setposrsp() {
  set_has_setposrsp();
  if (setposrsp_ == NULL) {
    setposrsp_ = new ::ActorSetPosRsp;
  }
  // @@protoc_insertion_point(field_mutable:UniverseMsgBody.setPosRsp)
  return setposrsp_;
}
inline ::ActorSetPosRsp* UniverseMsgBody::release_setposrsp() {
  // @@protoc_insertion_point(field_release:UniverseMsgBody.setPosRsp)
  clear_has_setposrsp();
  ::ActorSetPosRsp* temp = setposrsp_;
  setposrsp_ = NULL;
  return temp;
}
inline void UniverseMsgBody::set_allocated_setposrsp(::ActorSetPosRsp* setposrsp) {
  delete setposrsp_;
  setposrsp_ = setposrsp;
  if (setposrsp) {
    set_has_setposrsp();
  } else {
    clear_has_setposrsp();
  }
  // @@protoc_insertion_point(field_set_allocated:UniverseMsgBody.setPosRsp)
}

// -------------------------------------------------------------------

// UniverseMsg

// required .UniverseMsgHead msgHead = 1;
inline bool UniverseMsg::has_msghead() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UniverseMsg::set_has_msghead() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UniverseMsg::clear_has_msghead() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UniverseMsg::clear_msghead() {
  if (msghead_ != NULL) msghead_->::UniverseMsgHead::Clear();
  clear_has_msghead();
}
inline const ::UniverseMsgHead& UniverseMsg::msghead() const {
  // @@protoc_insertion_point(field_get:UniverseMsg.msgHead)
  return msghead_ != NULL ? *msghead_
                         : *::UniverseMsgHead::internal_default_instance();
}
inline ::UniverseMsgHead* UniverseMsg::mutable_msghead() {
  set_has_msghead();
  if (msghead_ == NULL) {
    msghead_ = new ::UniverseMsgHead;
  }
  // @@protoc_insertion_point(field_mutable:UniverseMsg.msgHead)
  return msghead_;
}
inline ::UniverseMsgHead* UniverseMsg::release_msghead() {
  // @@protoc_insertion_point(field_release:UniverseMsg.msgHead)
  clear_has_msghead();
  ::UniverseMsgHead* temp = msghead_;
  msghead_ = NULL;
  return temp;
}
inline void UniverseMsg::set_allocated_msghead(::UniverseMsgHead* msghead) {
  delete msghead_;
  msghead_ = msghead;
  if (msghead) {
    set_has_msghead();
  } else {
    clear_has_msghead();
  }
  // @@protoc_insertion_point(field_set_allocated:UniverseMsg.msgHead)
}

// optional .UniverseMsgBody msgBody = 2;
inline bool UniverseMsg::has_msgbody() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UniverseMsg::set_has_msgbody() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UniverseMsg::clear_has_msgbody() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UniverseMsg::clear_msgbody() {
  if (msgbody_ != NULL) msgbody_->::UniverseMsgBody::Clear();
  clear_has_msgbody();
}
inline const ::UniverseMsgBody& UniverseMsg::msgbody() const {
  // @@protoc_insertion_point(field_get:UniverseMsg.msgBody)
  return msgbody_ != NULL ? *msgbody_
                         : *::UniverseMsgBody::internal_default_instance();
}
inline ::UniverseMsgBody* UniverseMsg::mutable_msgbody() {
  set_has_msgbody();
  if (msgbody_ == NULL) {
    msgbody_ = new ::UniverseMsgBody;
  }
  // @@protoc_insertion_point(field_mutable:UniverseMsg.msgBody)
  return msgbody_;
}
inline ::UniverseMsgBody* UniverseMsg::release_msgbody() {
  // @@protoc_insertion_point(field_release:UniverseMsg.msgBody)
  clear_has_msgbody();
  ::UniverseMsgBody* temp = msgbody_;
  msgbody_ = NULL;
  return temp;
}
inline void UniverseMsg::set_allocated_msgbody(::UniverseMsgBody* msgbody) {
  delete msgbody_;
  msgbody_ = msgbody;
  if (msgbody) {
    set_has_msgbody();
  } else {
    clear_has_msgbody();
  }
  // @@protoc_insertion_point(field_set_allocated:UniverseMsg.msgBody)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::UniverseMsgId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::UniverseMsgId>() {
  return ::UniverseMsgId_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_universe_5fcs_2eproto__INCLUDED
