//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: universe_cs.proto
namespace universe_cs
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UniverseMsgHead")]
  public partial class UniverseMsgHead : global::ProtoBuf.IExtensible
  {
    public UniverseMsgHead() {}
    
    private int _msgId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int msgId
    {
      get { return _msgId; }
      set { _msgId = value; }
    }
    private int _actorId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"actorId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int actorId
    {
      get { return _actorId; }
      set { _actorId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActorRegisteReq")]
  public partial class ActorRegisteReq : global::ProtoBuf.IExtensible
  {
    public ActorRegisteReq() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActorRegisteRsp")]
  public partial class ActorRegisteRsp : global::ProtoBuf.IExtensible
  {
    public ActorRegisteRsp() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActorLoginReq")]
  public partial class ActorLoginReq : global::ProtoBuf.IExtensible
  {
    public ActorLoginReq() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActorLoginRsp")]
  public partial class ActorLoginRsp : global::ProtoBuf.IExtensible
  {
    public ActorLoginRsp() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActorLogoutReq")]
  public partial class ActorLogoutReq : global::ProtoBuf.IExtensible
  {
    public ActorLogoutReq() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActorLogoutRsp")]
  public partial class ActorLogoutRsp : global::ProtoBuf.IExtensible
  {
    public ActorLogoutRsp() {}
    
    private int _reserve = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"reserve", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int reserve
    {
      get { return _reserve; }
      set { _reserve = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActorGetFullDataReq")]
  public partial class ActorGetFullDataReq : global::ProtoBuf.IExtensible
  {
    public ActorGetFullDataReq() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActorPos")]
  public partial class ActorPos : global::ProtoBuf.IExtensible
  {
    public ActorPos() {}
    
    private int _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActorGetFullDataRsp")]
  public partial class ActorGetFullDataRsp : global::ProtoBuf.IExtensible
  {
    public ActorGetFullDataRsp() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private ActorPos _pos = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActorPos pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActorSetPosReq")]
  public partial class ActorSetPosReq : global::ProtoBuf.IExtensible
  {
    public ActorSetPosReq() {}
    
    private ActorPos _pos = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActorPos pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActorSetPosRsp")]
  public partial class ActorSetPosRsp : global::ProtoBuf.IExtensible
  {
    public ActorSetPosRsp() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PathNode")]
  public partial class PathNode : global::ProtoBuf.IExtensible
  {
    public PathNode() {}
    
    private int _pos_x = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }
    private int _pos_y = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pos_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pos_y
    {
      get { return _pos_y; }
      set { _pos_y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActorMoveReq")]
  public partial class ActorMoveReq : global::ProtoBuf.IExtensible
  {
    public ActorMoveReq() {}
    
    private readonly global::System.Collections.Generic.List<PathNode> _paths = new global::System.Collections.Generic.List<PathNode>();
    [global::ProtoBuf.ProtoMember(1, Name=@"paths", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PathNode> paths
    {
      get { return _paths; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActorMoveRsp")]
  public partial class ActorMoveRsp : global::ProtoBuf.IExtensible
  {
    public ActorMoveRsp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatInfo")]
  public partial class ChatInfo : global::ProtoBuf.IExtensible
  {
    public ChatInfo() {}
    
    private ChatType _type = ChatType.CHAT_TYPE_PRIVATE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ChatType.CHAT_TYPE_PRIVATE)]
    public ChatType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _content = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private ulong _dstId = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"dstId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong dstId
    {
      get { return _dstId; }
      set { _dstId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatReq")]
  public partial class ChatReq : global::ProtoBuf.IExtensible
  {
    public ChatReq() {}
    
    private ChatInfo _chatInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"chatInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ChatInfo chatInfo
    {
      get { return _chatInfo; }
      set { _chatInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatRsp")]
  public partial class ChatRsp : global::ProtoBuf.IExtensible
  {
    public ChatRsp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ForwardChatInfo")]
  public partial class ForwardChatInfo : global::ProtoBuf.IExtensible
  {
    public ForwardChatInfo() {}
    
    private ChatInfo _chatInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"chatInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ChatInfo chatInfo
    {
      get { return _chatInfo; }
      set { _chatInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LearnSpellReq")]
  public partial class LearnSpellReq : global::ProtoBuf.IExtensible
  {
    public LearnSpellReq() {}
    
    private int _spellId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"spellId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int spellId
    {
      get { return _spellId; }
      set { _spellId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LearnSpellRsp")]
  public partial class LearnSpellRsp : global::ProtoBuf.IExtensible
  {
    public LearnSpellRsp() {}
    
    private int _spellId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"spellId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int spellId
    {
      get { return _spellId; }
      set { _spellId = value; }
    }
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CastSpellReq")]
  public partial class CastSpellReq : global::ProtoBuf.IExtensible
  {
    public CastSpellReq() {}
    
    private int _spellId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"spellId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int spellId
    {
      get { return _spellId; }
      set { _spellId = value; }
    }
    private ulong _targetId = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"targetId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong targetId
    {
      get { return _targetId; }
      set { _targetId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CastSpellRsp")]
  public partial class CastSpellRsp : global::ProtoBuf.IExtensible
  {
    public CastSpellRsp() {}
    
    private int _spellId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"spellId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int spellId
    {
      get { return _spellId; }
      set { _spellId = value; }
    }
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UniverseMsgBody")]
  public partial class UniverseMsgBody : global::ProtoBuf.IExtensible
  {
    public UniverseMsgBody() {}
    
    private ActorRegisteReq _registeReq = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"registeReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActorRegisteReq registeReq
    {
      get { return _registeReq; }
      set { _registeReq = value; }
    }
    private ActorRegisteRsp _registeRsp = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"registeRsp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActorRegisteRsp registeRsp
    {
      get { return _registeRsp; }
      set { _registeRsp = value; }
    }
    private ActorLoginReq _loginReq = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"loginReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActorLoginReq loginReq
    {
      get { return _loginReq; }
      set { _loginReq = value; }
    }
    private ActorLoginRsp _loginRsp = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"loginRsp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActorLoginRsp loginRsp
    {
      get { return _loginRsp; }
      set { _loginRsp = value; }
    }
    private ActorLogoutReq _logoutReq = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"logoutReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActorLogoutReq logoutReq
    {
      get { return _logoutReq; }
      set { _logoutReq = value; }
    }
    private ActorLogoutRsp _logoutRsp = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"logoutRsp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActorLogoutRsp logoutRsp
    {
      get { return _logoutRsp; }
      set { _logoutRsp = value; }
    }
    private ActorGetFullDataReq _getFullDataReq = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"getFullDataReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActorGetFullDataReq getFullDataReq
    {
      get { return _getFullDataReq; }
      set { _getFullDataReq = value; }
    }
    private ActorGetFullDataRsp _getFullDataRsp = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"getFullDataRsp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActorGetFullDataRsp getFullDataRsp
    {
      get { return _getFullDataRsp; }
      set { _getFullDataRsp = value; }
    }
    private ActorSetPosReq _setPosReq = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"setPosReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActorSetPosReq setPosReq
    {
      get { return _setPosReq; }
      set { _setPosReq = value; }
    }
    private ActorSetPosRsp _setPosRsp = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"setPosRsp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActorSetPosRsp setPosRsp
    {
      get { return _setPosRsp; }
      set { _setPosRsp = value; }
    }
    private ActorMoveReq _moveReq = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"moveReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActorMoveReq moveReq
    {
      get { return _moveReq; }
      set { _moveReq = value; }
    }
    private ActorMoveRsp _moveRsp = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"moveRsp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ActorMoveRsp moveRsp
    {
      get { return _moveRsp; }
      set { _moveRsp = value; }
    }
    private ChatReq _chatReq = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"chatReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ChatReq chatReq
    {
      get { return _chatReq; }
      set { _chatReq = value; }
    }
    private ChatRsp _chatRsp = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"chatRsp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ChatRsp chatRsp
    {
      get { return _chatRsp; }
      set { _chatRsp = value; }
    }
    private ForwardChatInfo _forwardChatInfo = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"forwardChatInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ForwardChatInfo forwardChatInfo
    {
      get { return _forwardChatInfo; }
      set { _forwardChatInfo = value; }
    }
    private LearnSpellReq _learnSpellReq = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"learnSpellReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public LearnSpellReq learnSpellReq
    {
      get { return _learnSpellReq; }
      set { _learnSpellReq = value; }
    }
    private LearnSpellRsp _learnSpellRsp = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"learnSpellRsp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public LearnSpellRsp learnSpellRsp
    {
      get { return _learnSpellRsp; }
      set { _learnSpellRsp = value; }
    }
    private CastSpellReq _castSpellReq = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"castSpellReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CastSpellReq castSpellReq
    {
      get { return _castSpellReq; }
      set { _castSpellReq = value; }
    }
    private CastSpellRsp _castSpellRsp = null;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"castSpellRsp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CastSpellRsp castSpellRsp
    {
      get { return _castSpellRsp; }
      set { _castSpellRsp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UniverseMsg")]
  public partial class UniverseMsg : global::ProtoBuf.IExtensible
  {
    public UniverseMsg() {}
    
    private UniverseMsgHead _msgHead;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgHead", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public UniverseMsgHead msgHead
    {
      get { return _msgHead; }
      set { _msgHead = value; }
    }
    private UniverseMsgBody _msgBody = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"msgBody", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public UniverseMsgBody msgBody
    {
      get { return _msgBody; }
      set { _msgBody = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"UniverseMsgId")]
    public enum UniverseMsgId
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNIVERSE_MSG_ID_ACTOR_REGISTE_REQ", Value=1)]
      UNIVERSE_MSG_ID_ACTOR_REGISTE_REQ = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNIVERSE_MSG_ID_ACTOR_REGISTE_RSP", Value=2)]
      UNIVERSE_MSG_ID_ACTOR_REGISTE_RSP = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNIVERSE_MSG_ID_ACTOR_LOGIN_REQ", Value=3)]
      UNIVERSE_MSG_ID_ACTOR_LOGIN_REQ = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNIVERSE_MSG_ID_ACTOR_LOGIN_RSP", Value=4)]
      UNIVERSE_MSG_ID_ACTOR_LOGIN_RSP = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNIVERSE_MSG_ID_ACTOR_LOGOUT_REQ", Value=5)]
      UNIVERSE_MSG_ID_ACTOR_LOGOUT_REQ = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNIVERSE_MSG_ID_ACTOR_LOGOUT_RSP", Value=6)]
      UNIVERSE_MSG_ID_ACTOR_LOGOUT_RSP = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNIVERSE_MSG_ID_ACTOR_GET_FULL_DATA_REQ", Value=7)]
      UNIVERSE_MSG_ID_ACTOR_GET_FULL_DATA_REQ = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNIVERSE_MSG_ID_ACTOR_GET_FULL_DATA_RSP", Value=8)]
      UNIVERSE_MSG_ID_ACTOR_GET_FULL_DATA_RSP = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNIVERSE_MSG_ID_ACTOR_SET_POS_REQ", Value=9)]
      UNIVERSE_MSG_ID_ACTOR_SET_POS_REQ = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNIVERSE_MSG_ID_ACTOR_SET_POS_RSP", Value=10)]
      UNIVERSE_MSG_ID_ACTOR_SET_POS_RSP = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNIVERSE_MSG_ID_ACTOR_MOVE_REQ", Value=11)]
      UNIVERSE_MSG_ID_ACTOR_MOVE_REQ = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNIVERSE_MSG_ID_ACTOR_MOVE_RSP", Value=12)]
      UNIVERSE_MSG_ID_ACTOR_MOVE_RSP = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNIVERSE_MSG_ID_CHAT_REQ", Value=13)]
      UNIVERSE_MSG_ID_CHAT_REQ = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNIVERSE_MSG_ID_CHAT_RSP", Value=14)]
      UNIVERSE_MSG_ID_CHAT_RSP = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNIVERSE_MSG_ID_FORWRARD_CHAT", Value=15)]
      UNIVERSE_MSG_ID_FORWRARD_CHAT = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNIVERSE_MSG_ID_LEARN_SPELL_REQ", Value=16)]
      UNIVERSE_MSG_ID_LEARN_SPELL_REQ = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNIVERSE_MSG_ID_LEARN_SPELL_RSP", Value=17)]
      UNIVERSE_MSG_ID_LEARN_SPELL_RSP = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNIVERSE_MSG_ID_CAST_SPELL_REQ", Value=18)]
      UNIVERSE_MSG_ID_CAST_SPELL_REQ = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNIVERSE_MSG_ID_CAST_SPELL_RSP", Value=19)]
      UNIVERSE_MSG_ID_CAST_SPELL_RSP = 19
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ChatType")]
    public enum ChatType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_TYPE_PRIVATE", Value=1)]
      CHAT_TYPE_PRIVATE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_TYPE_AROUND", Value=2)]
      CHAT_TYPE_AROUND = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_TYPE_BROADCAST", Value=3)]
      CHAT_TYPE_BROADCAST = 3
    }
  
}