#ifndef  __UV_BATTLE_CONST_H__
#define  __UV_BATTLE_CONST_H__


enum UV_SPELL_EFFECT_TYPE
{
	UV_SPELL_EFFECT_DEC_INVALID = 0,
	UV_SPELL_EFFECT_DEC_HP,
	UV_SPELL_EFFECT_INC_HP,
	UV_SPELL_EFFECT_DEC_MP,
	UV_SPELL_EFFECT_INC_MP,
};

enum UV_UNIT_STATE_TYPE
{
	UV_UNIT_STATE_INVALID = 0,
	UV_UNIT_STATE_ALIVE = 1,
	UV_UNIT_STATE_DEAD = 2,
};

enum ACTOR_ATTR_TYPE
{
	ACTOR_ATTR_HP = 0,
	ACTOR_ATTR_MP = 1,
	ACTOR_ATTR_DAMAGE = 2,
	ACTOR_ATTR_DEFNED = 3,
	ACTOR_ATTR_TYPE_MAX = 4,
};

#endif // ! __UV_BATTLE_CONST_H__
